# Generated by Django 4.0 on 2021-12-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('comments', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AchieveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateTimeField(auto_now_add=True)),
                ('child_id', models.ManyToManyField(related_name='achievement', to='kidsachieve.Child')),
                ('work_id', models.ManyToManyField(related_name='work', to='kidsachieve.Work')),
            ],
        ),
    ]
