# Generated by Django 4.0 on 2022-01-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('point', models.IntegerField(default=10)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('nick_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AchieveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('date_done', models.DateTimeField(auto_now_add=True)),
                ('benefit_point', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('child_nick', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsachieve.child')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('work_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsachieve.work')),
            ],
        ),
    ]
