# Generated by Django 4.0 on 2022-01-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsachieve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievelist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='user_id',
            new_name='user',
        ),
    ]
