# Generated by Django 4.0 on 2021-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsachieve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='last_name',
        ),
        migrations.AddField(
            model_name='child',
            name='nick_name',
            field=models.CharField(db_index=True, default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
