# Generated by Django 4.0 on 2022-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsachieve', '0002_rename_user_id_achievelist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
