# Generated by Django 4.0 on 2022-01-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kidsachieve', '0003_alter_work_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AchieveList',
            new_name='Achievement',
        ),
    ]
